name: seslen_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

#------------------ PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter
  
  #İkon paketi için
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0

  #Mikrofon butonuna hareketli animasyon eklemek için
  avatar_glow: ^2.0.2

  #Sesi metne çevirmek için
  speech_to_text: ^6.4.0

  #Video oynatıcısı için
  video_player: ^2.8.1
  chewie: ^1.7.1

  #bottom navbar için
  custom_line_indicator_bottom_navbar: ^0.0.8

  # Splash ekranı için
  flutter_native_splash: ^2.4.1

# ----------------------- ./ PACKAGES END ----------------------- #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

#-------------- Native Splash Oluşturma --------------#
# Terminale şunu yaz: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/splash-logo.png
  image_dark: assets/logos/splash-logo.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/splash-logo.png
    image_dark: assets/logos/splash-logo.png
  
  web: false
#------------------------ ./ ------------------------#


flutter:
  uses-material-design: true

  # ----------------------- LOCAL ASSETS ----------------------- #
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/video_data.json

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700